# rules.py — trolling_baseline v1.2.0
# GENERATED BY agent:engineer · stage: SHADOW · hash: b3f9…
#
# CONTRACT (docs/07):
#   - pure functions: f(snapshot, targets) → intent dict
#   - imports: allowlist only (math, statistics)
#   - no I/O, no clocks (use snapshot["timestamp_ms"]), no state between calls
#   - every output clamped to the declared [safety] envelope in playbook.toml
#   - every function carries provenance in its docstring or Stage 2 rejects it

import math

# Declared envelope — mirrored from playbook.toml [safety].
# The Stage 2 AST gate verifies these constants are the clamps actually used.
MAX_RUDDER_STEP_DEG = 3.0
MAX_THROTTLE_STEP_PCT = 8.0
THROTTLE_MIN_PCT, THROTTLE_MAX_PCT = 10.0, 40.0


def evaluate(snapshot: dict, targets: dict) -> dict:
    """Top-level entrypoint (playbook.toml [interface].entrypoints)."""
    throttle = evaluate_propulsion(snapshot, targets)
    rudder = evaluate_steering(snapshot, targets)
    return {
        "requested_throttle_pct": throttle,
        "requested_rudder_deg": rudder,
        "horizon_s": 2.0,
    }


def evaluate_propulsion(snapshot: dict, targets: dict) -> float:
    """
    Rule: ramp throttle ~4% before headwind turns so the boat holds
    2.3 kn through the swing instead of falling off.

    Source: human.voice.transcript evt_01J3X… — "I always give her a bit
    before the turn or she falls off." (capt. r. delgado)
    Confidence: 0.87 — corroborated by 14 telemetry-aligned instances
    (mem:patterns/p_221, Analyst finding f_221).

    Envelope: |step| ≤ 8%/tick, absolute range 10–40%.
    """
    sog = snapshot["nav"]["sog_kn"]
    target_sog = targets.get("target_sog_kn", 2.3)
    wind_speed = snapshot["environment"]["wind_speed_kn"] or 0.0
    wind_angle = snapshot["environment"]["wind_angle_deg"]  # None = unknown
    current_throttle = snapshot["propulsion"]["throttle_pct"] or THROTTLE_MIN_PCT

    if sog is None:
        return current_throttle  # sensor gap: hold, never guess (A5)

    # Base P-term on speed error (I/D terms live in calibration namespace,
    # applied by the envelope-side controller, not here).
    error = target_sog - sog
    step = max(-MAX_THROTTLE_STEP_PCT, min(MAX_THROTTLE_STEP_PCT, error * 6.0))

    # Headwind pre-ramp: wind within 30° of the bow and building.
    if wind_angle is not None and abs(wind_angle) < 30.0 and wind_speed > 12.0:
        step += 4.0

    proposed = current_throttle + step
    return _clamp(proposed, THROTTLE_MIN_PCT, THROTTLE_MAX_PCT)


def evaluate_steering(snapshot: dict, targets: dict) -> float:
    """
    Rule: damp swing on a following sea — counter the compass swing rate
    rather than chasing the heading error directly.

    Source: mem:patterns/p_198 (Analyst extraction, 22 instances), captain
    confirmed in escalation e_7103: "yeah, you're steering the wiggle out."
    Confidence: 0.91.

    Envelope: |rudder request| ≤ 3°/tick (envelope clamps to ±15° absolute).
    """
    heading = snapshot["nav"]["heading_deg"]
    track = targets.get("target_track_deg")
    swing = snapshot["nav"]["swing_rate_dps"] or 0.0

    if heading is None or track is None:
        return 0.0  # hold course straight, let the human decide

    heading_error = _wrap_deg(track - heading)
    request = (heading_error * 0.4) - (swing * 0.6)
    return _clamp(request, -MAX_RUDDER_STEP_DEG, MAX_RUDDER_STEP_DEG)


def _clamp(value: float, lo: float, hi: float) -> float:
    """Every output path passes through a clamp — Stage 2 verifies this."""
    if math.isnan(value) or math.isinf(value):
        return lo  # fail to the bottom of range, never propagate garbage
    return max(lo, min(hi, value))


def _wrap_deg(delta: float) -> float:
    """Compass wrap: -180..180 so 359°→1° is +2, not -358."""
    return (delta + 180.0) % 360.0 - 180.0
